# name of the program (Minix service)
PROG=proj

.PATH: ${.CURDIR}/controllers/
.PATH: ${.CURDIR}/controllers/timer
.PATH: ${.CURDIR}/controllers/k&m
.PATH: ${.CURDIR}/controllers/graphics
.PATH: ${.CURDIR}/game
.PATH: ${.CURDIR}/sprites

# source code files to be compiled
SRCS = main.c utils.c timer.c KBC.c keyboard.c

# additional compilation flags
# "-Wall -Wextra -Werror -I . -std=c11 -Wno-unused-parameter" are already set
CFLAGS += -pedantic

# list of library dependencies (for Lab 2, only LCF library)
DPADD += ${LIBLCF}
LDADD += -llcf

# include LCOM's makefile that does all the "heavy lifting"
.include <minix.lcom.mk>